language: php
sudo: false
php:
- 5.3
- 5.4
- 5.5
- 5.6
- hhvm
matrix:
  allow_failures:
  - php: 5.3
  - php: 5.6
  - php: hhvm
env:
  matrix:
  - MAGENTO_VERSION=magento-ce-1.9.1.0
  - MAGENTO_VERSION=magento-ce-1.8.1.0
  - MAGENTO_VERSION=magento-ce-1.7.0.2
  - MAGENTO_VERSION=magento-ce-1.6.2.0
  global:
    secure: TP0IM6NkA+IlrCXcibsavEOiAvqeaZcHsDFE+O3Dh+wtupAUIt361pBhqqt1aXliuftdRWWyp1DMKIpBF8hTHwusgJyyRVAhAZy9U6WvPbFG/OTCRrDPrAFOOjAP3/3Vqu8qTYmIpqX7NpeUFcSJjpmjs4Sdd7LSfy+JLF77jLk=
script:
- curl -sSL https://raw.githubusercontent.com/ffuenf/MageTestStand/master/setup.sh | bash
notifications:
  slack:
    secure: XzC0gq5diGLgn0ALLdCGqo2/KGxdczxYPCLPHDzkAQ4XEO7NQ9X1NoSmFOl/fFe0qFHj7RZP7ybKCgmqqma/Ja9HcOHR0cdwP7knmtDegpua9rDlmPxH2fdgt6PQQY2VfJFhuCmHHtgWaEAP4Ok4dGv9YTG4KkVHtXtgReS24qQ=
